/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CMpHtml: typeof import('./components/CMpHtml/index.vue')['default']
    CPractice: typeof import('./components/CPractice/index.vue')['default']
    CZPaging: typeof import('./components/CZPaging/index.vue')['default']
    MentalArithmetic: typeof import('./components/CPractice/components/MentalArithmetic.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheFooter: typeof import('./components/TheFooter.vue')['default']
    TheInput: typeof import('./components/TheInput.vue')['default']
    TheLogo: typeof import('./components/TheLogo.vue')['default']
  }
}
